### ISSUE TITLE
blockchain.elrondProxy is not exported

### ISSUE THREAD

**Issue by HarleyAppleChoi** [ElrondNetwork/elrond-sdk-erdgo#29]
Is there a reason for that be not exported? If I want to query functions by the same gateway, do I need to call blockchain.NewElrondProxy(examples.TestnetGateway, nil) all over the program but not parsing the blockchain.elrondProxy instance?

Please export the type.

**Comment by bogdan-rosianu** [comment]
Hello. Yes, this is a pattern we use everywhere in our codebase. The structs are unexported. You don't have to initialize it every time, you can simply re-use the elrondProxy object obtained by NewElrondProxy

We won't make it exported as the entire struct relies on the fact the the object is well-constructed (which is obtained by calling the constructor)
